# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-15 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='username',
            new_name='user',
        ),
    ]
